### ISSUE TITLE
Lists?

### ISSUE THREAD

**Issue by edsu** [eramdam/tokimeki-mastodon#1]
This is a very useful tool, and so simple to run! 🙇 

This is just a suggestion to consider: would it be useful to allow users to assign accounts to particular lists while reviewing?

**Comment by eramdam** [comment]
I considered it at first, the original tool has it, but lists in Mastodon are quite different from Twitter's in that you need to follow someone to add them to a list which I feel would defeat the purpose of cleaning up your feed 😅

**Comment by edsu** [comment]
Yes, I understand the difference! I think assigning people to lists is a type of "cleaning" especially since Hometown supports [exclusive lists](https://github.com/hometown-fork/hometown/wiki/Exclusive-lists), which means you don't see posts in your home timeline that are present in a list.

**Comment by eramdam** [comment]
@edsu I have a deploy preview with the lists feature live on https://tokimeki-mastodon-7ogbxaewc-eramdam.vercel.app/ if you want to test!

**Comment by edsu** [comment]
@eramdam it works great! The only thing I could think of adding would be some kind of indication if the user is already on a list.

**Comment by eramdam** [comment]
@edsu went back and added an indicator for that. I might push this live next week.
